Fixed CI and improved developer docs
Shrinks99/NatronGitHub.github.io pull request #9
Opened 2024-06-24 18:36 UTC by Songtech-0912

Just some functional changes to get things working:

- GitHub action completely rewritten to support our external plugins that GitHub by default does not support
- Since we are using GitHub actions for Jekyll, I've bumped the Ruby version to a modern version to make `bundler` work both locally and on CI, it is in `.ruby-version`
- Improved docs (and new ones for building on windows) because setting Jekyll up properly is _way_ harder than it seems and can take up to an entire morning of troubleshooting
- CI works now!

2024-06-25 02:42 UTC, Shrinks99 requested changes
Thanks for the improved developer documentation!  That's really great!

> Extracted the homepage's text contents to YAML files in _data/ which should make it much more maintainable

I disagree with some of this.  Makes complete sense for the application files which should be auto-generated based on this data file, makes much less sense for all of the homepage text.

Generally I prefer to move things to data files that have many types of the same data that can be re-used in other places.  The homepage text does not meet this criteria.  In my opinion, this is now less maintainable as there is more abstraction which serves no purpose.  Please revert that change?

The social / community one I could take or leave, but again I think data files are the wrong use case for it.  If you wanted to make it a component so it was easy to drop into other pages, that might make sense!

2024-06-25 02:46 UTC, Shrinks99 commented on DEVELOP.md
> +Instructions will be fleshed-out in time, but for now, follow the same steps as in the GNU/Linux guide, with the one difference being that you want to use Homebrew to install `rbenv`, by running `bre
See Google's guidelines on [writing timeless documentation](https://developers.google.com/style/timeless-documentation).  Don't make promises for the future, instead word things the way they are currently, that way folks aren't left hoping for a guide that may never arrive!

```suggestion
Follow the same steps as in the GNU/Linux guide, with the one difference being that you want to use Homebrew to install `rbenv`, by running `brew install rbenv`. The remainder of the steps should be exactly the same as on GNU/Linux.
```

2024-06-27 23:08 UTC, Songtech-0912 commented
Added in the changes you requested :) let me know if there is anything else important.

2024-06-27 23:57 UTC, Shrinks99 approved these changes

2024-06-27 23:58 UTC, merged